from util import by_id

class PythonCSPBackend:
    @classmethod
    def codegen(self, kinda_ast):
        steps = kinda_ast[0][2]
        start_event = list(filter(lambda n: n[0] == "startEvent", steps))[0]
        steps_by_id = by_id(steps)

        func_map = {
            "endEvent": "end_event",
            "manualTask": "manual_task",
            "parallelGateway": "parallel_gateway",
            "scriptTask": "script_task",
            "startEvent": "start_event",
        }

        def outgoing(step):
            return list(filter(lambda n: n[0] == "outgoing", step[2]))

        def form_csp(step):
            f = func_map[step[0]]
            id = step[1]["id"]
            config = step[2]
            outgoing_steps = map(lambda s: steps_by_id[s[2]], outgoing(step))
            ks = list(map(form_csp, outgoing_steps))
            ks_len = len(ks)
            if ks_len == 0:
                k = "identity"
            elif ks_len > 1:
                k = f"fan_out([{', '.join(ks)}])"
            else:
                k = ks[0]
            csp = f"{f}(\"{id}\", {config}, {k})"
            return csp

        csp = form_csp(start_event)
        process_id = kinda_ast[0][1]["id"]
        code = "\n".join([
            Templates.preamble(), 
            Templates.main(process_id, csp)
        ])

        return code

#
# Templates for generated file
#

class Templates:
    @staticmethod
    def main(process_id, csp):
        return f"""

#
# Workflow expressed in CSP style. Would allow starting from/resuming at any point
#
workflow = {csp}

if __name__ == "__main__":
    print("Running '{process_id}'...")
    
    result = workflow({{}})
    print(f"result: {{result}}")
"""

    def preamble():
        # TODO only build preamble with what is needed by the workflow
        # TODO strategy for splitting these out into "lib" packages available to the
        #   compiled program.
        #
        #   from supreme_spoon.python_csp.runtime import fan_out, identity
        #   from supreme_spoon.python_cps.cli import manual_task
        #
        #   currently we have "static linking", perhaps keep that as an option as well.
        return """
# GENERATED BY supreme-spoon

#
# This is an early POC to demonstrate compiling BPMN diagrams to a static Python file.
#

#
# Example runtime
#

def configs_named(config, name):
    return list(filter(lambda c: c[0] == name, config))

def config_named(config, name):
    return configs_named(config, name)[0]

def config_value_named(config, name):
    return config_named(config, name)[2]

def ext_named(config, ext_name):
    ext_elems = config_named(config, 'extensionElements')
    return configs_named(ext_elems[2], ext_name)[0]

def ext_value_named(config, ext_name):
    return ext_named(config, ext_name)[2]

def fan_out(ks):
    def impl(data):
        results = [k(data) for k in ks]
        for result in results:
            if result is not None:
                return result
    return impl

identity = lambda x: x

#
# Example bpmn element implementations
#

def end_event(id, config, k):
    def impl(data):
        print(f"In end_event: {id}")
        return k(data)
    return impl

def manual_task(id, config, k):
    import os
    prompt = ext_value_named(config, 'instructionsForEndUser')
    def impl(data):
        print(f"In manual_task: {id}")
        input(prompt)
        print(config)
        return k(data)
    return impl

pg_instances = {}
def parallel_gateway(id, config, k):
    def make():
        expected_in = len(configs_named(config, 'incoming'))
        conds = {"let_in": 0}

        def impl(data):
            assert conds["let_in"] < expected_in
            conds["let_in"] += 1
            if conds["let_in"] != expected_in:
                return None
            print(f"In parallel_gateway: {id}")
            return k(data)
        return impl
    if id not in pg_instances:
        pg_instances[id] = make()
    return pg_instances[id]

def script_task(id, config, k):
    script = config_value_named(config, 'script')
    def impl(data):
        print(f"In script_task: {id} - {script}")
        data[f"result_{id}"] = f"TODO_EVAL({script})"
        return k(data)
    return impl

def start_event(id, config, k):
    def impl(data):
        print(f"In start_event: {id}")
        return k(data)
    return impl
"""
